    variables:
  buildTimeStamp:

trigger:
  branches:
    exclude:
    - '*'
schedules:
- cron: "30 02 * * *" # cron syntax defining a schedule in UTC
  displayName: 'Daily at 9.30PM EST' 
  branches:
    include: 
    - '*'
    
  always: true 
pool:
    vmImage: 'windows-latest'
stages:
- stage: _default
  jobs:
  - job: Job
    steps:
    - task: PowerShell@2
      displayName: Set variable BackupTimeStamp
      inputs:
        targetType: 'inline' #Timestamp variable gets time in UTC
        script: |
            $date=$(Get-Date -Format yyyy-MM-dd_HH.mm); 
            $str= "BackupRepo_"
            $str1=$str+$date;
            Write-Host "##vso[task.setvariable variable=buildTimeStamp]$str1" 
    - task: AzureCLI@2
      displayName: Delete backups older than 10 days
      inputs:
        azureSubscription: testrepo_serviceconnection #Service connection is created between Azure devops and Azure subcription that hosts the storage account
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az storage blob delete-batch -s devopsbackup --account-name <storage account name>--if-unmodified-since $(date -d `"10 days ago`" ''+%Y-%m-%dT%H:%MZ'')'
    - task: CmdLine@2
      displayName: Clone devops GIT repo
      inputs:
        script: git clone --mirror https://$(AZDevops_PAT)@dev.azure.com/<Organizaion Name>/<project name>/_git/TestRepo #PAT is stored as a secret variable in the pipeline
    - task: ArchiveFiles@2
      displayName: Create Zip file
      inputs:
        rootFolderOrFile: $(System.DefaultWorkingDirectory)
        includeRootFolder: true 
        archiveType: 'zip' # Options: zip, 7z, tar, wim
        #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(buildTimeStamp).zip' 
        replaceExistingArchive: false 
        verbose: true # Optional
    - task: AzureFileCopy@4
      displayName: Azure copy to storage account
      inputs:
        sourcePath: $(Build.ArtifactStagingDirectory)/*
        azureSubscription: testrepo_serviceconnection
        destination: azureBlob
        storage: '<storage account name>'
        containerName: 'devopsbackup'
        cleanTargetBeforeCopy: false # Optional